version: '3.8'

services:

  gateway:
    image: nginx:1.25.2-alpine
    hostname: gateway
    container_name: gateway
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - ${PORT}:80
    depends_on:
      - frontend
      - server
    restart: unless-stopped

  postgres:
    image: postgres:16rc1-alpine3.18
    hostname: postgres
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  server:
    container_name: server
    hostname: server
    build:
      context: ./server
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}
    depends_on:
      - postgres
    restart: unless-stopped

  frontend:
    container_name: frontend
    hostname: frontend
    build:
      context: ./frontend
    depends_on:
      - server
    restart: unless-stopped

  # ------------------------------
  # Demo agents
  # ------------------------------
  wikipedia-agent:
    build: ./wikipedia-agent
    container_name: wikipedia-agent
    hostname: wikipedia-agent
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - AGENTLABS_SERVER_URL=http://server:3000
    depends_on:
      - server

volumes:
  postgres-data:
