version: '3.8'

services:
  server:
    container_name: server
    hostname: server
    build:
      context: ./server
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    environment:
      - PORT=${SERVER_PORT}
    restart: unless-stopped

  frontend:
    container_name: frontend
    hostname: frontend
    environment:
      - PUBLIC_SERVER_URL=${SERVER_URL}
    build:
      context: ./frontend
    ports:
      - ${FRONTEND_PORT}:3000
    restart: unless-stopped

  # demo agents
  wikipedia-agent:
    build: ./wikipedia-agent
    container_name: wikipedia-agent
    hostname: wikipedia-agent
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - AGENTLABS_SERVER_URL=http://server:${SERVER_PORT}
    depends_on:
      - server
