version: '3.8'

volumes:
  postgres-data:

services:

  gateway:
    image: ${CADDY_IMAGE}
    volumes:
      - ./caddy/config/Caddyfile:/etc/caddy/Caddyfile
    ports:
      - ${PORT}:80
    depends_on:
      - frontend
      - server
    restart: unless-stopped

  frontend:
    image: ${FRONTEND_IMAGE}
    depends_on:
      - server
    restart: unless-stopped

  console:
    image: ${CONSOLE_IMAGE}
    depends_on:
      - server
    restart: unless-stopped

  postgres:
    image: ${POSTGRES_IMAGE}
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  server:
    image: ${SERVER_IMAGE}
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}
      - USERS_ACCESS_TOKEN_SECRET=${USERS_ACCESS_TOKEN_SECRET}
      - MEMBERS_ACCESS_TOKEN_SECRET=${MEMBERS_ACCESS_TOKEN_SECRET}
      - MEMBERS_AUTH_CODE_EXPIRATION_DELAY_IN_MINUTES=${MEMBERS_AUTH_CODE_EXPIRATION_DELAY_IN_MINUTES}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - EMAIL_SENDER_ADDRESS=${EMAIL_SENDER_ADDRESS}
      - EMAIL_SENDER_NAME=${EMAIL_SENDER_NAME}
      - USERS_OAUTH_GOOGLE_CLIENT_ID=${USERS_OAUTH_GOOGLE_CLIENT_ID}
      - USERS_OAUTH_GOOGLE_CLIENT_SECRET=${USERS_OAUTH_GOOGLE_CLIENT_SECRET}
    depends_on:
      - postgres
    restart: unless-stopped
