version: '3.8'

volumes:
  postgres-data:

networks:
  # We explicitly define a subnet to avoid unintentional shadowing
  default:
    ipam:
      config:
        - subnet: 172.20.0.0/24

services:

  gateway:
    image: ${CADDY_IMAGE}
    volumes:
      - ./caddy/config/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/data:/data
    ports:
      - ${PORT}:80
    depends_on:
      - frontend
      - server
    restart: unless-stopped

  frontend:
    image: ${FRONTEND_IMAGE}
    depends_on:
      - server
    restart: unless-stopped
    environment:
      - PUBLIC_APP_HOST=${PUBLIC_AI_AGENT_DOMAIN}

  console:
    image: ${CONSOLE_IMAGE}
    environment:
      - PUBLIC_AI_AGENT_DOMAIN=${PUBLIC_AI_AGENT_DOMAIN}
      - PUBLIC_OAUTH_GOOGLE_CLIENT_ID=${PUBLIC_OAUTH_GOOGLE_CLIENT_ID}
      - PUBLIC_TELEMETRY_KEY=${PUBLIC_TELEMETRY_KEY}
      - PUBLIC_DISCORD_URL=${PUBLIC_DISCORD_URL}
      - PUBLIC_INTERCOM_APP_ID=${INTERCOM_APP_ID}
    depends_on:
      - server
    restart: unless-stopped

  postgres:
    image: ${POSTGRES_IMAGE}
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  server:
    image: ${SERVER_IMAGE}
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      - USERS_ACCESS_TOKEN_SECRET=${USERS_ACCESS_TOKEN_SECRET}
      - MEMBERS_ACCESS_TOKEN_SECRET=${MEMBERS_ACCESS_TOKEN_SECRET}
      - MEMBERS_AUTH_CODE_EXPIRATION_DELAY_IN_MINUTES=${MEMBERS_AUTH_CODE_EXPIRATION_DELAY_IN_MINUTES}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - EMAIL_SENDER_ADDRESS=${EMAIL_SENDER_ADDRESS}
      - EMAIL_SENDER_NAME=${EMAIL_SENDER_NAME}
      - USERS_OAUTH_GOOGLE_CLIENT_ID=${USERS_OAUTH_GOOGLE_CLIENT_ID}
      - USERS_OAUTH_GOOGLE_CLIENT_SECRET=${USERS_OAUTH_GOOGLE_CLIENT_SECRET}
    depends_on:
      - postgres
    restart: unless-stopped
