env:
  BUILD_CONTEXT: frontend

name: Check frontend
on:
  push:

jobs:
  build:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v3

      # Required to compile the client SDKS on runners without built-in node suppot
      - uses: actions/setup-node@v3
        with:
          node-version: '>= 20'

      - name: Compile SDKs
        run: |
          docker build -f ./server/print-oas.Dockerfile -t print-oas ./server
          docker run --rm print-oas > ./server/openapi.yaml
          # dispose of the image to avoid bloating the runner (especially if self hosted)
          docker rmi print-oas
          sh build-clients.sh

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.BUILD_CONTEXT }}
          push: false
