env:
  BUILD_CONTEXT: frontend

name: Check frontend

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Required to compile the client SDKS on runners without built-in node suppot
      - uses: actions/setup-node@v3
        with:
          node-version: '>= 20'

      - name: Compile SDKs
        run: |
          docker build -f ./server/print-oas.Dockerfile -t print-oas ./server
          docker run --rm print-oas > ./server/openapi.yaml
          docker rmi print-oas
          OPENAPI_BASE=/api ./build-clients.sh

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.BUILD_CONTEXT }}
          push: false
