name: Deploy to cloud

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup ssh
        run: |
          echo ${{ secrets.DEPLOY_SSH_PRIVATE_KEY_B64 }} | base64 -d > /tmp/privkey
          chmod 400 /tmp/privkey

      - name: Pull latest images
        run: ssh -i /tmp/privkey -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} 'cd agentlabs && docker compose pull'

      - name: Up
        run: ssh -i /tmp/privkey -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} 'cd agentlabs && docker compose up --build --force-recreate -d'
