name: Publish python sdk
env:
  PUBLISHER_IMAGE_TAG: python-sdk-publisher

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  publish_pypi:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v3
      - name: Build python sdk publisher image
        run:  |
          docker build sdks/python-sdk -t $PUBLISHER_IMAGE_TAG
      - name: Publish python client
        env:
          PYPI_USERNAME: agentlabs
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
          VERSION: ${{ github.ref_name }}
        run: |
          docker run --rm $PUBLISHER_IMAGE_TAG
