name: Publish python sdk
env:
  PUBLISHER_IMAGE_TAG: python-sdk-publisher

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  publish_pypi:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v3
      - name: Build python sdk publisher image
        run:  |
          docker build sdks/python-sdk -t $PUBLISHER_IMAGE_TAG
      - name: Publish python client (tag version)
        run: >
          docker run
          --rm
          -e PYPI_USER="${{ vars.PYPI_USER }}"
          -e PYPI_PASSWORD="${{ secrets.PYPI_PASSWORD }}"
          -e VERSION="$( echo \"${{ github.ref_name }}\" | tr -d 'v' )"
          $PUBLISHER_IMAGE_TAG
